site_name: 'teste-go'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/vitor-savicki/teste-go
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: 'docs/index.md'
